### ISSUE TITLE
一些微小的工作

### ISSUE THREAD

**Issue by JFlmTul** [MagaFun/anti-aq-list#3]
我拉黑的比较少其实，而且都很主观。所以就列出几个我觉得进list完全没错的吧。我觉得不太好直接pull进去，就提一个issues给参考吧。

下面这俩是16年10月广州cicf活动之后我拉黑的，记不清当时什么情况了，应该是给μ's哭丧的同时黑水，同期进我黑名单的还有一些是已经列出的那几个。

[三森梨彩_武道馆厨](http://weibo.com/Mimorinsky) 曾用名：三森家洗脚婢_武道馆完成
![image](https://cloud.githubusercontent.com/assets/19582838/21952576/cd8bbfdc-da5b-11e6-8a01-786b862fcd04.png)

[孤独星空传奇X](http://weibo.com/u/2934781773) ：这个是我在拉黑上面那个的时候一起找到的。其实在上图相关的转发评论里面找，特别方便。

还有著名的拉拉吐槽君：[Lovelive吐槽君](http://weibo.com/722567360)

以及缺德社：[第三新缺德社](http://weibo.com/u/5824652670)

总结一句，人啊，不能让自己活的太可怜。
就算活的可怜也别给μ‘s抹黑。
# 一群废物。

**Comment by MagaFun** [comment]
首先感谢您的贡献。其实直接 pull request 是可以的，我会一个人一个人侦察一下然后考虑是否加入。其实跟提 issue 差不多。

*三森梨彩_武道馆厨*和*孤独星空传奇X*将加入名单。

关于*Lovelive吐槽君*以及*缺德社*，由于这两位并没有显著的**反 LoveLive! Sunshine!!**倾向，待定是否加入。

不过多说几句，这俩人确实挺恶心的，就是加进一个黑水列表不太合适，如果这两位确实发过什么黑水的内容的话将会加入。

再次感谢您的贡献。

**Comment by JFlmTul** [comment]
可以。我列出来那俩营销号主要是因为对整个LL企划来说，他俩都是可以直接拉进黑名单的。不过只是黑水的黑名单里的确没有必要把他们特别加进去。

晚上有空的话我会再找找。毕竟点草垃圾也是我的兴趣之一。
